pipeline {
    agent any
    stages {

        stage('install packages') {
            steps {
                sh '''
                cd post_send_message_endpoint/
                npm install --production
                '''
            }
        }

        stage('Clean Zip') {
            steps {
                sh 'rm ./post_send_message_endpoint/index.zip'
            }
        }

        stage('Zip up Lambda') {
            steps {
                zip zipFile: 'post_send_message_endpoint/index.zip', archive: false, dir: 'post_send_message_endpoint'
            }
        }

        stage('Deploy') {
            steps {
                sh 'aws lambda update-function-code --function-name twilio-send-message --zip-file fileb://post_send_message_endpoint/index.zip'
            }
        }
    }
}