pipeline {
    agent any
    stages {

        stage('install packages') {
            steps {
                sh '''
                cd get_messages_endpoint/
                npm install
                '''
            }
        }

        stage('Clean Zip') {
            steps {
                sh 'rm ./get_messages_endpoint/index.zip'
            }
        }

        stage('Zip up Lambda') {
            steps {
                zip zipFile: 'get_messages_endpoint/index.zip', archive: false, dir: 'get_messages_endpoint'
            }
        }

        stage('Deploy') {
            steps {
                sh 'aws lambda update-function-code --function-name twilio-list-messages --zip-file fileb://get_messages_endpoint/index.zip'
            }
        }
    }
}