pipeline {
    agent any
    stages {

        stage('Clean Zip') {
            steps {
                sh 'rm -rf ./get_messages_endpoint/index.zip'
            }
        }

        stage('Zip up Lambda') {
            steps {
                zip zipFile: 'get_messages_endpoint/index.zip', archive: false, dir: 'get_messages_endpoint'
            }
        }

        stage('Deploy') {
            steps {
                sh 'aws lambda update-function-code --function-name twilio-list-messages --zip-file ./get_messages_endpoint/index.zip'
            }
        }
    }
}